name:                seasoned-pine
version:             0.1.0.0
github:              "isovector/seasoned-pine"
license:             BSD3
author:              "Sandy Maguire"
maintainer:          "sandy@sandymaguire.me"
copyright:           "2018 Sandy Maguire"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on Github at <https://github.com/isovector/seasoned-pine#readme>

dependencies:
- base >= 4.7 && < 5
- newtype-generics
- containers
- time
- lens
- errors
- mtl

library:
  source-dirs: src

executables:
  seasoned-pine-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - seasoned-pine

tests:
  seasoned-pine-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - seasoned-pine
